---
- hosts: all
  vars:
    ansible_python_interpreter: python3
  tasks:
    - name: install pip3
      become: true
      apt:
        name: python3-pip
    - name: pip3 install docker lib python for ansible
      pip:
        name: docker
    - name: Install node-exporter for linux
      docker_container:
        name: 'node_exporter_linux'
        image: bitnami/node-exporter
        state: 'started'
        ports:
          - "9100:9100"
      register: db_cont_metadata
