route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'slack_general'
receivers:
- name: 'slack_general'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/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'
    channel: '#prometheus'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
