version: '3.3'

networks:
  webnetwork:
    driver: bridge

volumes:
  prometheus_data:


services:
  prometheus:
    hostname: prometheus
    # image: prom/prometheus
    image: bitnami/prometheus:2.24.1-debian-10-r20
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-admin-api"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
      #- "--storage.tsdb.retention.time=1y"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./targets.json:/etc/prometheus/targets.json
      - ./prometheus_rules.yml:/etc/prometheus/prometheus_rules.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - cadvisor
    networks:
      - webnetwork
  alertmanager:
    image: bitnami/alertmanager:latest
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./config.yml:/opt/bitnami/alertmanager/conf/config.yml
    networks:
      - webnetwork
  node_exporter:
    image: bitnami/node-exporter
    container_name: node-exporter
    ports:
      - 9100:9100
    networks:
      - webnetwork
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    depends_on:
      - redis
    networks:
      - webnetwork
  redis:
    image: library/redis:latest
    container_name: redis
    ports:
    - 6379:6379
    networks:
      - webnetwork
  grafana:
    #image: grafana/grafana
    image: grafana/grafana:7.3.7-ubuntu
    container_name: grafana
    ports:
    - 3000:3000
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=admin123"
    networks:
      - webnetwork

