# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 15s
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "prometheus_rules.yml"
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.



scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    scrape_interval: 5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
    scrape_timeout: 5s
    static_configs:
      - targets: ['51.255.211.183:9090']

  - job_name: 'metric-types'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '164.132.212.98:8080' ]
    # drop a node with its label
    #metric_relabel_configs:
    #  - source_labels: [image]
    #    regex: '.*/(.*)'
    #    replacement: '$1'
    #    target_label: id
    #relabel_configs:
    #  - source_labels: [__address__]
    #    regex: '192.xx.xx.xx'
    #    action: drop

  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: [ '51.68.28.191:18080' ]


  - job_name: 'node'
    file_sd_configs:
    - files:
      - 'targets.json'














